### ISSUE TITLE
Potensial Copy and Paste mistake

### ISSUE THREAD

**Issue by HirbodBehnam** [cbeuw/Cloak-panel#1]
Hello
Take a look at this line:
https://github.com/cbeuw/Cloak-panel/blob/master/script/endpoint.js#L74
I know that you are multiplying other values in 2^20 to convert them to Megabyte/s. But I think you made a small mistake on this one. Why are you multiplying Epoch time in 2^20 :D

**Comment by cbeuw** [comment]
Good catch! I should refrain from coding when it's way past my bed time...

**Comment by HirbodBehnam** [comment]
Lol
Anyway thanks for the great project and protocol. With this type of user management, everyone can write their own client for admin panel. Very very thank you!
